### ISSUE TITLE
Please make sure to add release notes for v0.9.0

### ISSUE THREAD

**Issue by zachgersh** [bosh-packages/golang-release#10]
Pretty sure this is going to happen for future releases as well. Maybe want to automate a potential way to note the released version of go that is shipping as part of the bump?

**Comment by aaronshurley** [comment]
and now v0.10.0, please!

**Comment by dpb587-pivotal** [comment]
Added notes for [v0.9.0](https://github.com/bosh-packages/golang-release/releases/tag/v0.9.0) and [v0.10.0](https://github.com/bosh-packages/golang-release/releases/tag/v0.10.0); thanks for the reminders.

Currently the GitHub release publishing steps are manual. I agree it would be nice to automate at some point to not have to worry about it.
