### ISSUE TITLE
update pipeline to support 1.12 now that it is out

### ISSUE THREAD

**Issue by zachgersh** [bosh-packages/golang-release#14]
Seems like the pipeline `dynamic-metalink` resource is going to need a bit of an update since 1.12 shipped.

cc @dpb587-pivotal

**Comment by dpb587** [comment]
Might be required to configure `GOCACHE` when adding 1.12 support (requested in #12). I saw the following error from my binary's `packaging` script when it was trying to autoupgrade go ([patch](https://github.com/dpb587/ssoca-bosh-release/commit/6d148c0f2150a851fac7a536a032e0a360c14145)).

>     build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined

**Comment by edwardecook** [comment]
We'd be keen to see this added to golang-release as soon as possible as we are planning to bump to Golang 1.12 this month if possible. We would happily contribute although we don't know the process.

cc @jimbo459

**Comment by kieron-dev** [comment]
Services Enablement are also keen to see 1.12 added here. We would like to release soon with go-1.12 so would like an idea of if / when 1.12 will be added, so we can manually add a go-1.12 tarball if necessary.

**Comment by mrosecrance** [comment]
1.12 is now added. For future reference, everything is pipelined so the work is largely a find and replace as shown [here](https://github.com/bosh-packages/golang-release/commit/ee2dd311dce5d5468d195d91fb4be3155c3292a3) (there was also some GoCache stuff). I'm waiting on getting added to this repo to close this issue.
