### ISSUE TITLE
Add golang-stable-* and golang-old-stable-* packages

### ISSUE THREAD

**Issue by winkingturtle-vmw** [bosh-packages/golang-release#27]
[Github action ](https://github.com/actions/setup-go?tab=readme-ov-file#v3) now supports having `stable` and `old-stable` version instead of having to update the version every few months. Recently we had to keep both supported golang version for windows-tools-release since some of our concourse workers needed to stay behind while others could be moved forward. We've opt-in for an actual version number to get around this and added a second package, but it'd be great if we could've used `old-stable` instead so that we don't have to keep updating it. 

What are you thoughts about adding 12 more packages to this release

- golang-old-stable-darwin-test
- golang-old-stable-darwin
-  golang-old-stable-linux-test
- golang-old-linux-darwin
- golang-old-stable-windows-test
- golang-old-stable-windows
- golang-stable-darwin-test
- golang-stable-darwin
-  golang-stable-linux-test
- golang-stable-linux-darwin
- golang-stable-windows-test
- golang-stable-windows

**Comment by rkoster** [comment]
what about `golang-previous-stable-linux-darwin`?

**Comment by winkingturtle-vmw** [comment]
I have done a bit more digging into this and I am not sure if I like my original suggestion due to the fact that at some point there will be a Go 2.x and I am don't know what would  `stable`, `old-stable`, or `previous-stable` would mean in that case. We have gotten around this issue for now.
