### ISSUE TITLE
Autobump golang-release when a new go version is released

### ISSUE THREAD

**Issue by bsnchan** [bosh-packages/golang-release#4]
It would be great if golang-release is auto-bumped every time a new version of go is released. This way, downstream dependencies can get auto-bumped as well.

**Comment by dpb587-pivotal** [comment]
I imagine this would be convenient. Are you familiar with any releases which implement this sort of auto-bumping in their pipelines which could be used for workflow inspiration?

**Comment by frodenas** [comment]
@dpb587-pivotal For inspiration, take a look at the [shield-boshrelease](https://github.com/starkandwayne/shield-boshrelease/blob/master/ci/settings.yml#L49) pipeline. When a new version of shield is detected, it runs a script to [update-blobs](https://github.com/starkandwayne/shield-boshrelease/blob/master/ci/scripts/update-blob). @drnic can provide more details, as he is the original author.

**Comment by alex-slynko** [comment]
Here is how concourse bumps go version https://github.com/concourse/concourse/commit/cf0d93d7140b7625b342af890eefbf220460086a

**Comment by cppforlife** [comment]
@alex-slynko dont see any checksums.

**Comment by alex-slynko** [comment]
@cppforlife 

You can get latest blob from 
https://storage.googleapis.com/golang/go1.9.4.linux-amd64.tar.gz
and sha256 for it from https://storage.googleapis.com/golang/go1.9.4.linux-amd64.tar.gz.sha256

To be honest, I am little bit worried that getting new packages is not at least half-automated (Concourse can create pull requests). CF CLI, Ruby and Golang have not be updated for more than a month and all have old versions of packages.

**Comment by zachgersh** [comment]
here' we go - now this is achievable due to the addition of

https://golang.org/dl/?mode=json

**Comment by zachgersh** [comment]
@cppforlife - I think we can close this now?

**Comment by dpb587-pivotal** [comment]
[Story #158044891](https://www.pivotaltracker.com/story/show/158044891) about this is pending acceptance; then we'll be able to close this.

**Comment by zachgersh** [comment]
@dpb587-pivotal - new golang release is out. This pipeline working?

**Comment by dpb587-pivotal** [comment]
Looks like it failed on the `1.10.4` bump; thanks. Internally tracking that failure [here](https://www.pivotaltracker.com/story/show/160069129).

We probably should have closed this issue after originally implementing... but now let's close it after this new story/fix.

**Comment by jfmyers9** [comment]
This should be fixed as of: e87468137cb6e8f5637c967667c46dbd302e886d.
