### ISSUE TITLE
golang 1.10.2 && 1.9.6 are both released

### ISSUE THREAD

**Issue by zachgersh** [bosh-packages/golang-release#8]
please bump 💃 

### 1.10.2 Release Notes
https://github.com/golang/go/milestone/73?closed=1

### 1.9.6 Release Notes
https://github.com/golang/go/milestone/74?closed=1

**Comment by dpb587-pivotal** [comment]
Wouldn't it be nice if this were automated...

Related to #4.

**Comment by alex-slynko** [comment]
1.9.7 & 1.10.3 are there.

**Comment by cppforlife** [comment]
superseded by 1.9.7 and 1.10.3 shipped in latest release.
